# Generated by Django 3.1.2 on 2021-12-06 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoitem',
            name='videoLink',
            field=models.CharField(default='https://www.youtube.com/watch?v=FzigMMY9yig', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoitem',
            name='videoTitle',
            field=models.CharField(default='Dovydas video', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoitem',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
