# Generated by Django 3.1.2 on 2021-12-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0002_auto_20211206_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoitem',
            name='votes',
        ),
    ]
