# Generated by Django 3.1.2 on 2021-12-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0004_auto_20211214_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinformation',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone number'),
        ),
    ]
